updates to clone modules and sync modules

diff --git a/bin/build/build-js b/bin/build/build-js
--- a/bin/build/build-js
+++ b/bin/build/build-js
@@ -30,23 +30,23 @@ while getopts "$options" opt ; do
     c )
       configuration="$OPTARG"
       ;;
-    h )
-      >&2 printf -- "%b" "$usage_long" && exit 1
+   h )
+      >&2 printf -- "%b\n" "$usage_long"
       exit 0
       ;;
     \?)
-      >&2 printf -- "%b" "unknown option: -$OPTARG"
-      >&2 printf -- "%b" "$usage_short"
+      >&2 printf -- "unknown option: -%b\n" "$OPTARG"
+      >&2 printf -- "%b\n" "$usage_short"
       exit 1
       ;;
     : )
-      >&2 printf -- "%b" "missing option argument for -$OPTARG"
-      >&2 printf -- "%b" "$usage_short"
+      >&2 printf -- "missing option argument for -%b\n" "$OPTARG"
+      >&2 printf -- "%b\n" "$usage_short"
       exit 1
       ;;
     * )
-      >&2 printf -- "%b" "unimplemented option: -$OPTARG"
-      >&2 printf -- "%b" "$usage_short"
+      >&2 printf -- "unimplemented option: -%b\n" "$OPTARG"
+      >&2 printf -- "%b\n" "$usage_short"
       exit 1
     esac
 done
@@ -57,15 +57,15 @@ if [ "$latest" = true ] ; then
 fi
 
 if [ "$version" = "" ] ; then
-  >&2 printf "%b- must specify a JS version to build (-l or -v version) -%b" "$RED" "$NC"
+  >&2 printf "%b- must specify a JS version to build (-l or -v version) -%b\n" "$RED" "$NC"
   exit 1
 fi
 
 
->&2 printf -- "- executing sync-js %s -" "$version"
+>&2 printf -- "- executing sync-js %s -\n" "$version"
 sync-js "$revision"
 
->&2 printf -- "- cleaning previous build and artifacts -"
+>&2 printf -- "- cleaning previous build and artifacts -\n"
 rimraf "$JS_BUILD_ROOT"
 rimraf "$JS_ARTIFACTS_ROOT"
 
@@ -75,11 +75,11 @@ pushj "$JS_SYNC_ROOT" >/dev/null
   cp -rf ./ "$JS_BUILD_ROOT"
 popj >/dev/null
 
->&2 printf -- "- building js version %s -" "$version"
+>&2 printf -- "- building js version %s -\n" "$version"
 pushj "$JS_BUILD_ROOT" >/dev/null
   npm run deploy -c "$configuration"
 
-  >&2 printf -- "- downloading 64 bit node.exe to bin -"
+  >&2 printf -- "- downloading 64 bit node.exe to bin -\n"
   curl -sL http://nodejs.org/dist/latest/x64/node.exe >bin/node.exe
 popj >/dev/null
 
diff --git a/bin/build/build-net b/bin/build/build-net
--- a/bin/build/build-net
+++ b/bin/build/build-net
@@ -51,23 +51,23 @@ while getopts "$options" opt ; do
     o )
       output_path="$OPTARG"
       ;;
-    h )
-      >&2 printf -- "%b" "$usage_long" && exit 1
+   h )
+      >&2 printf -- "%b\n" "$usage_long"
       exit 0
       ;;
     \?)
-      >&2 printf -- "%b" "unknown option: -$OPTARG"
-      >&2 printf -- "%b" "$usage_short"
+      >&2 printf -- "unknown option: -%b\n" "$OPTARG"
+      >&2 printf -- "%b\n" "$usage_short"
       exit 1
       ;;
     : )
-      >&2 printf -- "%b" "missing option argument for -$OPTARG"
-      >&2 printf -- "%b" "$usage_short"
+      >&2 printf -- "missing option argument for -%b\n" "$OPTARG"
+      >&2 printf -- "%b\n" "$usage_short"
       exit 1
       ;;
     * )
-      >&2 printf -- "%b" "unimplemented option: -$OPTARG"
-      >&2 printf -- "%b" "$usage_short"
+      >&2 printf -- "unimplemented option: -%b\n" "$OPTARG"
+      >&2 printf -- "%b\n" "$usage_short"
       exit 1
     esac
 done
@@ -78,7 +78,7 @@ if [ "$latest" = true ] ; then
 fi
 
 if [ "$version" = "" ] ; then
-  >&2 printf -- "%b- must specify a version to build (-l or -v version) -%b" "$RED" "$NC"
+  >&2 printf -- "%b- must specify a version to build (-l or -v version) -%b\n" "$RED" "$NC"
   exit 1
 fi
 
@@ -88,7 +88,7 @@ msbuild_path="/c/Program Files (x86)/MSBuild/${tools_version}/Bin/MSBuild.exe"
 win_msbuild_path="$(cpath -w "$msbuild_path")"
 if [ ! -f "$msbuild_path" ] ; then
   # Not there, lets install
-  >&2 printf -- "%b- msbuild not found, installing... -%b" "$RED" "$NC"
+  >&2 printf -- "%b- msbuild not found, installing... -%b\n" "$RED" "$NC"
   choco install microsoft-build-tools
 
   # These downloads might help at some point
@@ -96,33 +96,33 @@ if [ ! -f "$msbuild_path" ] ; then
   #choco install netfx-4.5.2-devpack
 fi
 if [ ! -f "$msbuild_path" ] ; then
-  >&2 printf -- "%b- msbuild still not found... see if it is in default path -%b" "$RED" "$NC"
+  >&2 printf -- "%b- msbuild still not found... see if it is in default path -%b\n" "$RED" "$NC"
   msbuild_path="msbuild"
   win_msbuild_path="msbuild"
 fi
 
-printf -- "%b- executing sync-net %s -%b" "$CYAN" "$version" "$NC"
+printf -- "%b- executing sync-net %s -%b\n" "$CYAN" "$version" "$NC"
 sync-net "$version"
 
->&2 printf -- "- building and deploying artifacts version %s -" "$version"
+>&2 printf -- "- building and deploying artifacts version %s -\n" "$version"
 pushj "$NET_SYNC_ROOT" >/dev/null
-  >&2 printf -- "- restoring nuget packages -"
+  >&2 printf -- "- restoring nuget packages -\n"
   nuget restore Tix.SelfHost.sln -PackagesDirectory packages -Verbosity quiet -NonInteractive
 
-  >&2 printf -- "- cleaning %b -" "$NET_BUILD_ROOT"
+  >&2 printf -- "- cleaning %b -\n" "$NET_BUILD_ROOT"
   rimraf "$NET_BUILD_ROOT"
   mkdirp "$NET_BUILD_ROOT"
 
   win_net_build_root="$(cpath -w "$output_path")"
-  >&2 printf -- "- building to %s -" "$win_net_build_root"
+  >&2 printf -- "- building to %s -\n" "$win_net_build_root"
 
   msbuild_command="cmd //c \"$win_msbuild_path\" Tix.Web.SelfHost\\Tix.Web.SelfHost.csproj //tv:${tools_version} //nologo //p:VisualStudioVersion=${visual_studio_version} //p:Configuration=${configuration} //p:OutputPath=\"${win_net_build_root}\" //m //v:m //clp:ErrorsOnly"
-  >&2 printf -- "- executing... -> %s -" "$msbuild_command"
+  >&2 printf -- "- executing... -> %s -\n" "$msbuild_command"
   "$msbuild_command"
 
-  >&2 printf -- "- cleaning packages -"
+  >&2 printf -- "- cleaning packages -\n"
   rimraf packages
-  >&2 printf -- "- packages cleaned successfully -"
+  >&2 printf -- "- packages cleaned successfully -\n"
 popj >/dev/null
 
 if [ "$encrypt" = true ] ; then
@@ -131,4 +131,4 @@ if [ "$encrypt" = true ] ; then
   cryptkeeper -ens connectionStrings -p "${configuration}Provider" -C "${configuration}Keys" -E "$BUILD_ROOT" -R "$config_path"
 fi
 
->&2 printf -- "%b- tixinc-net version %s successfully built -%b" "$GREEN" "$version" "$NC"
+>&2 printf -- "%b- tixinc-net version %s successfully built -%b\n" "$GREEN" "$version" "$NC"
diff --git a/bin/clone/clone-module b/bin/clone/clone-module
--- a/bin/clone/clone-module
+++ b/bin/clone/clone-module
@@ -46,7 +46,7 @@ shift $((OPTIND-1))
 
 ### if no arguments, throw an error
 if [ $# -eq 0 ]; then
-  >&2 printf -- "%b- must specify a module to clone -%b" "$RED" "$NC"
+  >&2 printf -- "%b- must specify a module to clone -%b\n" "$RED" "$NC"
   exit 1
 fi
 
@@ -63,10 +63,10 @@ module_path="$module_root/$module_dir"
 
 ### if module already cloned, throw an error
 if [ -d "$module_path" ]; then
-  >&2 printf -- "%b- module %s already exists at %s -%b" "$CYAN" "$module_name" "$module_path" "$NC"
-  exit 1
+  >&2 printf -- "%b- module %s already exists at %s, skipping -%b\n" "$CYAN" "$module_name" "$module_path" "$NC"
+  exit 0
 fi
 
->&2 printf -- "- cloning %s to %s... -" "$module_url" "$module_path"
-git clone "$module_url" "$module_path" 2>&1 | grep -qi "fatal" && >&2 printf -- "An error occurred while cloning." && exit 1
->&2 printf -- "%b- %s cloned successfully -%b" "$GREEN" "$module_name" "$NC"
+>&2 printf -- "- cloning %s to %s... -\n" "$module_url" "$module_path"
+git clone "$module_url" "$module_path" 2>&1 | grep -qi "fatal" && >&2 printf -- "%b- an error occurred while cloning -%b\n" "$RED" "$NC" && exit 1
+>&2 printf -- "%b- %s cloned successfully -%b\n" "$GREEN" "$module_name" "$NC"
diff --git a/bin/release b/bin/release
--- a/bin/release
+++ b/bin/release
@@ -50,30 +50,30 @@ while getopts "$options" opt ; do
     n )
       net_version="$OPTARG"
       ;;
-    h )
-      >&2 printf -- "%b" "$usage_long" && exit 1
+   h )
+      >&2 printf -- "%b\n" "$usage_long"
       exit 0
       ;;
     \?)
-      >&2 printf -- "%b" "unknown option: -$OPTARG"
-      >&2 printf -- "%b" "$usage_short"
+      >&2 printf -- "unknown option: -%b\n" "$OPTARG"
+      >&2 printf -- "%b\n" "$usage_short"
       exit 1
       ;;
     : )
-      >&2 printf -- "%b" "missing option argument for -$OPTARG"
-      >&2 printf -- "%b" "$usage_short"
+      >&2 printf -- "missing option argument for -%b\n" "$OPTARG"
+      >&2 printf -- "%b\n" "$usage_short"
       exit 1
       ;;
     * )
-      >&2 printf -- "%b" "unimplemented option: -$OPTARG"
-      >&2 printf -- "%b" "$usage_short"
+      >&2 printf -- "unimplemented option: -%b\n" "$OPTARG"
+      >&2 printf -- "%b\n" "$usage_short"
       exit 1
     esac
 done
 shift $((OPTIND-1))
 
 if [ "$latest" = true ] ; then
-  >&2 printf "%b- latest (-l) flag specified, getting the latest annotated tagged versions of tixinc-js and tixinc-net -%b\n" "$CYAN" "$NC"
+  >&2 printf -- "%b- latest (-l) flag specified, getting the latest annotated tagged versions of tixinc-js and tixinc-net -%b\n" "$CYAN" "$NC"
   js_version=$(revisions -l tixinc-js)
   >&2 printf -- "%b- using js version %s -%b\n" "$CYAN" "$js_version" "$NC"
   net_version=$(revisions -l tixinc-net)
@@ -81,16 +81,16 @@ if [ "$latest" = true ] ; then
 fi
 
 if [ "$js_version" = "" ] ; then
-  >&2 printf "%b- tixinc-js (-j) version string is mandatory.  Use \"revisions -m tixinc-js\" to see recent versions -%b\n" "$RED" "$NC"
+  >&2 printf -- "%b- tixinc-js (-j) version string is mandatory.  Use \"revisions -m tixinc-js\" to see recent versions -%b\n" "$RED" "$NC"
   exit 1
 fi
 if [ "$net_version" = "" ] ; then
-  >&2 printf "%b- tixinc-net (-n) version string is mandatory.  Use \"revisions -m tixinc-net\" to see recent versions -%b\n" "$RED" "$NC"
+  >&2 printf -- "%b- tixinc-net (-n) version string is mandatory.  Use \"revisions -m tixinc-net\" to see recent versions -%b\n" "$RED" "$NC"
   exit 1
 fi
 
-configuration_lower="$(printf "%s" "$configuration" | tr '[:upper:]' '[:lower:]')"
-release_name="$(printf "net_%s-js_%s-%s" "$net_version" "$js_version" "$configuration_lower")"
+configuration_lower="$(printf -- "%s" "$configuration" | tr '[:upper:]' '[:lower:]')"
+release_name="$(printf -- "net_%s-js_%s-%s" "$net_version" "$js_version" "$configuration_lower")"
 >&2 printf -- "- building and packaging release %s -\n" "$release_name"
 if [ "$encrypt" = true ] ; then
   build-net -v "$net_version" -c "$configuration" -V 12.0 -e
