big changes

diff --git a/bin/build/build-js b/bin/build/build-js
--- a/bin/build/build-js
+++ b/bin/build/build-js
@@ -1,13 +1,113 @@
 #!/bin/bash
 #
-# Syncs an exact revision of tixinc-js module to the build directory.
+# Deploys fresh tixinc-js artifacts
 
-### if no arguments, throw an error
-if [ $# -lt 1 ]; then
-  >&2 echo "Must specify a revision to build..."
+set -e
+. "$HOME/.tixrc"
+
+latest=false
+version=""
+configuration="debug"
+
+usage_short="${BLUE}usage: build-js [-l] [-v version] [-c configuration]"
+usage_long="$usage_short\n-l: Deploy latest version of tixinc-js"
+usage_long="$usage_long\n-v: Deploy specific version (tag or hash)"
+usage_long="$usage_long\n-c: configuration to use (default: $configuration)${NC}"
+
+usage_short="$usage_short\nuse -h to get supported command information${NC}"
+
+options=":lv:c:h"
+shopt -u nocasematch
+OPTIND=1
+while getopts "$options" opt ; do
+    case "$opt" in
+    l )
+      latest=true
+      ;;
+    v )
+      version="$OPTARG"
+      ;;
+    c )
+      configuration="$OPTARG"
+      ;;
+    h )
+      >&2 printf "%b" "$usage_long" && exit 1
+      exit 0
+      ;;
+    \?)
+      >&2 printf "%b" "unknown option: -$OPTARG"
+      >&2 printf "%b" "$usage_short"
+      exit 1
+      ;;
+    : )
+      >&2 printf "%b" "missing option argument for -$OPTARG"
+      >&2 printf "%b" "$usage_short"
+      exit 1
+      ;;
+    * )
+      >&2 printf "%b" "unimplemented option: -$OPTARG"
+      >&2 printf "%b" "$usage_short"
+      exit 1
+    esac
+done
+shift $((OPTIND-1))
+
+if [ "$latest" = true ] ; then
+  version="$(revisions -l tixinc-js)"
+fi
+
+if [ "$version" = "" ] ; then
+  >&2 printf "%b- must specify a JS version to build (-l or -v version) -%b" "$RED" "$NC"
   exit 1
 fi
 
-. "$HOME/.tixrc"
 
-build-module tixinc-js "$1"
+>&2 printf -- "- executing sync-js %s -" "$version"
+sync-js "$revision"
+
+>&2 printf -- "- cleaning previous build and artifacts -"
+rimraf "$JS_BUILD_ROOT"
+rimraf "$JS_ARTIFACTS_ROOT"
+
+
+mkdirp "$JS_BUILD_ROOT"
+pushd "$JS_SYNC_ROOT" >/dev/null
+  cp -rf ./ "$JS_BUILD_ROOT"
+popd >/dev/null
+
+>&2 printf -- "- building js version %s -" "$version"
+pushj "$JS_BUILD_ROOT" >/dev/null
+  >&2 printf -- "- configuring JS as %s -" "$configuration"
+  server_config_path="server.json"
+  server_target_config_path="etc/${configuration}.json"
+
+  client_config_path="client/client.json"
+  client_config_path="client/etc/${configuration}.json"
+
+  if [ ! -f "$server_target_config_path" ] ; then
+    >&2 printf "%b- no target configuration exists at %s -%b" "$RED" "$server_target_config_path" "$NC"
+    exit 1
+  fi
+
+  if [ ! -f "$client_target_config_path" ] ; then
+    >&2 printf "%b- no target configuration exists at %s -%b" "$RED" "$client_target_config_path" "$NC"
+    exit 1
+  fi
+
+  cp "$server_target_config_path" "$server_config_path"
+  cp "$client_target_config_path" "$client_config_path"
+
+
+
+
+  >&2 printf -- "- installing npm build dependencies -"
+  npm install
+
+
+
+
+  >&2 printf -- "- downloading 64 bit node.exe to bin -"
+  curl -sL http://nodejs.org/dist/latest/x64/node.exe >bin/node.exe
+popj >/dev/null
+
+>&2 echo -e "${GREEN}--Artifacts revision $revision successfully deployed--${NC}"
diff --git a/bin/build/build-net b/bin/build/build-net
--- a/bin/build/build-net
+++ b/bin/build/build-net
@@ -1,16 +1,139 @@
 #!/bin/bash
 #
-# Syncs an exact revision of tixinc-net module to the build directory.
+# Deploys fresh tixinc-net artifacts
 
 set -e
-
 . "$HOME/.tixrc"
 
-### if no arguments, throw an error
-if [ $# -lt 1 ]; then
-  >&2 echo -e "${RED}--Must specify a revision to build...--${NC}"
+latest=false
+version=""
+tools_version="12.0"
+visual_studio_version="12.0"
+configuration="Debug"
+encrypt=false
+output_path="$NET_BUILD_ROOT"
+
+usage_short="${CYAN}Usage: build-net -l|-v version [-t ToolsVersion] [-V VisualStudioVersion] [-c Configuration] [-e] [-o OutputPath]"
+usage_long="$usage_short\n-l: deploy latest version of tixinc-net"
+usage_long="$usage_long\n-v: deploy specific version (tag or hash)"
+usage_long="$usage_long\n-t: msbuild ToolsVersion to use (default=${tools_version})"
+usage_long="$usage_long\n-V: msbuild VisualStudioVersion to use (default=${visual_studio_version})"
+usage_long="$usage_long\n-c: configuration to deploy (default=${configuration})"
+usage_long="$usage_long\n-e: encrypt configuration section"
+usage_long="$usage_long\n-o: output path (default=$output_path)${NC}"
+
+usage_short="$usage_short\nUse -h to get supported command information.${NC}"
+
+
+options=":lv:t:V:c:eo:h"
+shopt -u nocasematch
+OPTIND=1
+while getopts "$options" opt ; do
+    case "$opt" in
+    l )
+      latest=true
+      ;;
+    v )
+      version="$OPTARG"
+      ;;
+    t )
+      tools_version="$OPTARG"
+      ;;
+    V )
+      visual_studio_version="$OPTARG"
+      ;;
+    c )
+      configuration="$OPTARG"
+      ;;
+    e )
+      encrypt=true
+      ;;
+    o )
+      output_path="$OPTARG"
+      ;;
+    h )
+      >&2 echo -e "$usage_long" && exit 1
+      exit 0
+      ;;
+    \?)
+      >&2 echo -e "Unknown option: -$OPTARG"
+      >&2 echo -e "$usage_short"
+      exit 1
+      ;;
+    : )
+      >&2 echo -e "Missing option argument for -$OPTARG"
+      >&2 echo -e "$usage_short"
+      exit 1
+      ;;
+    * )
+      >&2 echo -e "Unimplemented option: -$OPTARG" && exit 1
+      >&2 echo -e "$usage_short"
+      exit 1
+    esac
+done
+shift $((OPTIND-1))
+
+if [ "$latest" = true ] ; then
+  version="$(revisions -l tixinc-net)"
+fi
+
+if [ "$version" = "" ] ; then
+  >&2 echo -e "${RED}--Must specify a version to build (-l or -v version)--${NC}"
   exit 1
 fi
 
+# msbuild might exist and be in path, might exist and not be in path or might not exist... thankfully MS makes this easy to install.. not
+# setup default paths an test to see if its there
+msbuild_path="/c/Program Files (x86)/MSBuild/${tools_version}/Bin/MSBuild.exe"
+win_msbuild_path="$(cpath -w "$msbuild_path")"
+if [ ! -f "$msbuild_path" ] ; then
+  # Not there, lets install
+  >&2 echo -e "${BLUE}--MSBUILD not found, installing...--${NC}"
+  choco install microsoft-build-tools
 
-build-module tixinc-net "$1"
+  # These downloads might help at some point
+  #http://download.microsoft.com/download/9/B/B/9BB1309E-1A8F-4A47-A6C5-ECF76672A3B3/BuildTools_Full.exe
+  #choco install netfx-4.5.2-devpack
+fi
+if [ ! -f "$msbuild_path" ] ; then
+  >&2 echo -e "${RED}--MSBUILD still not found... see if it is in default path--${NC}"
+  msbuild_path="msbuild"
+  win_msbuild_path="msbuild"
+fi
+
+
+echo "--executing sync-net $version--"
+sync-net "$version"
+
+>&2 echo "--Building and deploying artifacts version $version--"
+pushd "$NET_SYNC_ROOT" >/dev/null
+  >&2 echo "--Restoring packages--"
+  nuget restore Tix.SelfHost.sln -PackagesDirectory packages -Verbosity quiet -NonInteractive
+  >&2 echo "--Packages restored successfully--"
+
+  >&2 echo "--Cleaning $NET_ARTIFACTS_ROOT--"
+  rimraf "$NET_BUILD_ROOT"
+  rimraf "$NET_ARTIFACTS_ROOT"
+  mkdirp "$NET_BUILD_ROOT"
+  mkdirp "$NET_ARTIFACTS_ROOT"
+  >&2 echo "--MSBUILD artifacts--"
+
+  win_net_build_root="$(cpath -w "$output_path")"
+  >&2 echo "Building to $win_net_build_root"
+
+  >&2 echo "Executing... -> cmd /c \"$win_msbuild_path\" Tix.Web.SelfHost\Tix.Web.SelfHost.csproj /tv:${tools_version} /nologo /p:VisualStudioVersion=${visual_studio_version} /p:Configuration=${configuration} /p:OutputPath=\"${win_net_build_root}\" /m /v:m /clp:ErrorsOnly"
+  cmd //c "$win_msbuild_path" Tix.Web.SelfHost\\Tix.Web.SelfHost.csproj //tv:${tools_version} //nologo //p:VisualStudioVersion=${visual_studio_version} //p:Configuration=${configuration} //p:OutputPath="${win_net_build_root}" //m //v:m //clp:ErrorsOnly
+  >&2 echo "--MSBUILD finished successfully--"
+
+  >&2 echo "--Cleaning packages--"
+  rimraf packages
+  >&2 echo "--Packages cleaned successfully--"
+popd >/dev/null
+
+if [ "$encrypt" = true ] ; then
+  npm install -g cryptkeeper &>/dev/null
+  config_path="$NET_BUILD_ROOT/Tix.Web.SelfHost.exe.config"
+  cryptkeeper -ens connectionStrings -p "${configuration}Provider" -C "${configuration}Keys" -E "$BUILD_ROOT" -R "$config_path"
+fi
+
+>&2 echo -e "${GREEN}--NET version $version successfully built--${NC}"
