updates to deploy scripts

diff --git a/bin/build/build-js b/bin/build/build-js
--- a/bin/build/build-js
+++ b/bin/build/build-js
@@ -31,22 +31,22 @@ while getopts "$options" opt ; do
       configuration="$OPTARG"
       ;;
     h )
-      >&2 printf "%b" "$usage_long" && exit 1
+      >&2 printf -- "%b" "$usage_long" && exit 1
       exit 0
       ;;
     \?)
-      >&2 printf "%b" "unknown option: -$OPTARG"
-      >&2 printf "%b" "$usage_short"
+      >&2 printf -- "%b" "unknown option: -$OPTARG"
+      >&2 printf -- "%b" "$usage_short"
       exit 1
       ;;
     : )
-      >&2 printf "%b" "missing option argument for -$OPTARG"
-      >&2 printf "%b" "$usage_short"
+      >&2 printf -- "%b" "missing option argument for -$OPTARG"
+      >&2 printf -- "%b" "$usage_short"
       exit 1
       ;;
     * )
-      >&2 printf "%b" "unimplemented option: -$OPTARG"
-      >&2 printf "%b" "$usage_short"
+      >&2 printf -- "%b" "unimplemented option: -$OPTARG"
+      >&2 printf -- "%b" "$usage_short"
       exit 1
     esac
 done
@@ -71,21 +71,13 @@ rimraf "$JS_ARTIFACTS_ROOT"
 
 
 mkdirp "$JS_BUILD_ROOT"
-pushd "$JS_SYNC_ROOT" >/dev/null
+pushj "$JS_SYNC_ROOT" >/dev/null
   cp -rf ./ "$JS_BUILD_ROOT"
-popd >/dev/null
+popj >/dev/null
 
 >&2 printf -- "- building js version %s -" "$version"
 pushj "$JS_BUILD_ROOT" >/dev/null
-
-  >&2 printf -- "- installing npm build dependencies -"
-  npm install
-
-  >&2 printf -- "- configuring JS as %s -" "$configuration"
-  npm run configure "$configuration"
-
-  >&2 printf -- "- building js -"
-  npm run build
+  npm run deploy -c "$configuration"
 
   >&2 printf -- "- downloading 64 bit node.exe to bin -"
   curl -sL http://nodejs.org/dist/latest/x64/node.exe >bin/node.exe
diff --git a/bin/build/build-net b/bin/build/build-net
--- a/bin/build/build-net
+++ b/bin/build/build-net
@@ -52,22 +52,22 @@ while getopts "$options" opt ; do
       output_path="$OPTARG"
       ;;
     h )
-      >&2 echo -e "$usage_long" && exit 1
+      >&2 printf -- "%b" "$usage_long" && exit 1
       exit 0
       ;;
     \?)
-      >&2 echo -e "Unknown option: -$OPTARG"
-      >&2 echo -e "$usage_short"
+      >&2 printf -- "%b" "unknown option: -$OPTARG"
+      >&2 printf -- "%b" "$usage_short"
       exit 1
       ;;
     : )
-      >&2 echo -e "Missing option argument for -$OPTARG"
-      >&2 echo -e "$usage_short"
+      >&2 printf -- "%b" "missing option argument for -$OPTARG"
+      >&2 printf -- "%b" "$usage_short"
       exit 1
       ;;
     * )
-      >&2 echo -e "Unimplemented option: -$OPTARG" && exit 1
-      >&2 echo -e "$usage_short"
+      >&2 printf -- "%b" "unimplemented option: -$OPTARG"
+      >&2 printf -- "%b" "$usage_short"
       exit 1
     esac
 done
@@ -78,7 +78,7 @@ if [ "$latest" = true ] ; then
 fi
 
 if [ "$version" = "" ] ; then
-  >&2 echo -e "${RED}--Must specify a version to build (-l or -v version)--${NC}"
+  >&2 printf -- "%b- must specify a version to build (-l or -v version) -%b" "$RED" "$NC"
   exit 1
 fi
 
@@ -88,7 +88,7 @@ msbuild_path="/c/Program Files (x86)/MSBuild/${tools_version}/Bin/MSBuild.exe"
 win_msbuild_path="$(cpath -w "$msbuild_path")"
 if [ ! -f "$msbuild_path" ] ; then
   # Not there, lets install
-  >&2 echo -e "${BLUE}--MSBUILD not found, installing...--${NC}"
+  >&2 printf -- "%b- msbuild not found, installing... -%b" "$RED" "$NC"
   choco install microsoft-build-tools
 
   # These downloads might help at some point
@@ -96,39 +96,34 @@ if [ ! -f "$msbuild_path" ] ; then
   #choco install netfx-4.5.2-devpack
 fi
 if [ ! -f "$msbuild_path" ] ; then
-  >&2 echo -e "${RED}--MSBUILD still not found... see if it is in default path--${NC}"
+  >&2 printf -- "%b- msbuild still not found... see if it is in default path -%b" "$RED" "$NC"
   msbuild_path="msbuild"
   win_msbuild_path="msbuild"
 fi
 
-
-echo "--executing sync-net $version--"
+printf -- "%b- executing sync-net %s -%b" "$CYAN" "$version" "$NC"
 sync-net "$version"
 
->&2 echo "--Building and deploying artifacts version $version--"
-pushd "$NET_SYNC_ROOT" >/dev/null
-  >&2 echo "--Restoring packages--"
+>&2 printf -- "- building and deploying artifacts version %s -" "$version"
+pushj "$NET_SYNC_ROOT" >/dev/null
+  >&2 printf -- "- restoring nuget packages -"
   nuget restore Tix.SelfHost.sln -PackagesDirectory packages -Verbosity quiet -NonInteractive
-  >&2 echo "--Packages restored successfully--"
 
-  >&2 echo "--Cleaning $NET_ARTIFACTS_ROOT--"
+  >&2 printf -- "- cleaning %b -" "$NET_BUILD_ROOT"
   rimraf "$NET_BUILD_ROOT"
-  rimraf "$NET_ARTIFACTS_ROOT"
   mkdirp "$NET_BUILD_ROOT"
-  mkdirp "$NET_ARTIFACTS_ROOT"
-  >&2 echo "--MSBUILD artifacts--"
 
   win_net_build_root="$(cpath -w "$output_path")"
-  >&2 echo "Building to $win_net_build_root"
+  >&2 printf -- "- building to %s -" "$win_net_build_root"
 
-  >&2 echo "Executing... -> cmd /c \"$win_msbuild_path\" Tix.Web.SelfHost\Tix.Web.SelfHost.csproj /tv:${tools_version} /nologo /p:VisualStudioVersion=${visual_studio_version} /p:Configuration=${configuration} /p:OutputPath=\"${win_net_build_root}\" /m /v:m /clp:ErrorsOnly"
-  cmd //c "$win_msbuild_path" Tix.Web.SelfHost\\Tix.Web.SelfHost.csproj //tv:${tools_version} //nologo //p:VisualStudioVersion=${visual_studio_version} //p:Configuration=${configuration} //p:OutputPath="${win_net_build_root}" //m //v:m //clp:ErrorsOnly
-  >&2 echo "--MSBUILD finished successfully--"
+  msbuild_command="cmd //c \"$win_msbuild_path\" Tix.Web.SelfHost\\Tix.Web.SelfHost.csproj //tv:${tools_version} //nologo //p:VisualStudioVersion=${visual_studio_version} //p:Configuration=${configuration} //p:OutputPath=\"${win_net_build_root}\" //m //v:m //clp:ErrorsOnly"
+  >&2 printf -- "- executing... -> %s -" "$msbuild_command"
+  "$msbuild_command"
 
-  >&2 echo "--Cleaning packages--"
+  >&2 printf -- "- cleaning packages -"
   rimraf packages
-  >&2 echo "--Packages cleaned successfully--"
-popd >/dev/null
+  >&2 printf -- "- packages cleaned successfully -"
+popj >/dev/null
 
 if [ "$encrypt" = true ] ; then
   npm install -g cryptkeeper &>/dev/null
@@ -136,4 +131,4 @@ if [ "$encrypt" = true ] ; then
   cryptkeeper -ens connectionStrings -p "${configuration}Provider" -C "${configuration}Keys" -E "$BUILD_ROOT" -R "$config_path"
 fi
 
->&2 echo -e "${GREEN}--NET version $version successfully built--${NC}"
+>&2 printf -- "%b- tixinc-net version %s successfully built -%b" "$GREEN" "$version" "$NC"
diff --git a/bin/release b/bin/release
--- a/bin/release
+++ b/bin/release
@@ -13,17 +13,17 @@ fi
 latest=false
 configuration=Release
 encrypt=false
-release_root="$RELEASE_ROOT"
-js_revision=""
-net_revision=""
+artifacts_root="$RELEASE_ROOT"
+js_version=""
+net_version=""
 
-usage_short="${CYAN}Usage: release [-l] [-c configuration] [-e] [-d destination-path] [-j js-revision] [-n net-revision]"
+usage_short="${CYAN}Usage: release [-l] [-c configuration] [-e] [-d destination-path] [-j js-version] [-n net-version]"
 usage_long="$usage_short\n-l: deploy latest across all libraries"
 usage_long="$usage_long\n-c: configuration to deploy (default: $configuration)"
 usage_long="$usage_long\n-e: encrypt connection strings configuration (default: $encrypt)"
-usage_long="$usage_long\n-d: optional destination directory (default: $release_root)"
-usage_long="$usage_long\n-j: tixinc-js revision to deploy"
-usage_long="$usage_long\n-n: tixinc-net revision to deploy${NC}"
+usage_long="$usage_long\n-d: optional destination directory (default: $artifacts_root)"
+usage_long="$usage_long\n-j: tixinc-js version to deploy"
+usage_long="$usage_long\n-n: tixinc-net version to deploy${NC}"
 
 usage_short="$usage_short\nUse -h to get supported command information.${NC}"
 
@@ -42,31 +42,31 @@ while getopts "$options" opt ; do
       encrypt=true
       ;;
     d )
-      release_root="$OPTARG"
+      artifacts_root="$OPTARG"
       ;;
     j )
-      js_revision=$OPTARG
+      js_version="$OPTARG"
       ;;
     n )
-      net_revision=$OPTARG
+      net_version="$OPTARG"
       ;;
     h )
-      >&2 printf "%b" "$usage_long" && exit 1
+      >&2 printf -- "%b" "$usage_long" && exit 1
       exit 0
       ;;
     \?)
-      >&2 printf "%b" "unknown option: -$OPTARG"
-      >&2 printf "%b" "$usage_short"
+      >&2 printf -- "%b" "unknown option: -$OPTARG"
+      >&2 printf -- "%b" "$usage_short"
       exit 1
       ;;
     : )
-      >&2 printf "%b" "missing option argument for -$OPTARG"
-      >&2 printf "%b" "$usage_short"
+      >&2 printf -- "%b" "missing option argument for -$OPTARG"
+      >&2 printf -- "%b" "$usage_short"
       exit 1
       ;;
     * )
-      >&2 printf "%b" "unimplemented option: -$OPTARG"
-      >&2 printf "%b" "$usage_short"
+      >&2 printf -- "%b" "unimplemented option: -$OPTARG"
+      >&2 printf -- "%b" "$usage_short"
       exit 1
     esac
 done
@@ -74,40 +74,40 @@ shift $((OPTIND-1))
 
 if [ "$latest" = true ] ; then
   >&2 printf "%b- latest (-l) flag specified, getting the latest annotated tagged versions of tixinc-js and tixinc-net -%b\n" "$CYAN" "$NC"
-  js_revision=$(revisions -l tixinc-js)
-  >&2 printf -- "%b- using js version %s -%b\n" "$CYAN" "$js_revision" "$NC"
-  net_revision=$(revisions -l tixinc-net)
-  >&2 printf -- "%b- using net version %s -%b\n" "$CYAN" "$net_revision" "$NC"
+  js_version=$(revisions -l tixinc-js)
+  >&2 printf -- "%b- using js version %s -%b\n" "$CYAN" "$js_version" "$NC"
+  net_version=$(revisions -l tixinc-net)
+  >&2 printf -- "%b- using net version %s -%b\n" "$CYAN" "$net_version" "$NC"
 fi
 
-if [ "$js_revision" = "" ] ; then
-  >&2 printf "%b- tixinc-js (-j) revision string is mandatory.  Use \"revisions -m tixinc-js\" to see recent versions -%b\n" "$RED" "$NC"
+if [ "$js_version" = "" ] ; then
+  >&2 printf "%b- tixinc-js (-j) version string is mandatory.  Use \"revisions -m tixinc-js\" to see recent versions -%b\n" "$RED" "$NC"
   exit 1
 fi
-if [ "$net_revision" = "" ] ; then
-  >&2 printf "%b- tixinc-net (-n) revision string is mandatory.  Use \"revisions -m tixinc-net\" to see recent versions -%b\n" "$RED" "$NC"
+if [ "$net_version" = "" ] ; then
+  >&2 printf "%b- tixinc-net (-n) version string is mandatory.  Use \"revisions -m tixinc-net\" to see recent versions -%b\n" "$RED" "$NC"
   exit 1
 fi
 
 configuration_lower="$(printf "%s" "$configuration" | tr '[:upper:]' '[:lower:]')"
-release_name="$(printf "net_%s-js_%s-%s" "$net_revision" "$js_revision" "$configuration_lower")"
+release_name="$(printf "net_%s-js_%s-%s" "$net_version" "$js_version" "$configuration_lower")"
 >&2 printf -- "- building and packaging release %s -\n" "$release_name"
 if [ "$encrypt" = true ] ; then
-  build-net -v "$net_revision" -c "$configuration" -V 12.0 -e
+  build-net -v "$net_version" -c "$configuration" -V 12.0 -e
 else
-  build-net -v "$net_revision" -c "$configuration" -V 12.0
+  build-net -v "$net_version" -c "$configuration" -V 12.0
 fi
-build-js "$js_revision"
+build-js "$js_version"
 deploy-startup
-#deploy-rsa "$configuration"
 
-release_path="${release_root}/${release_name}.7z"
-mkdirp "$release_root"
+artifacts_path="${artifacts_root}/${release_name}.7z"
+rimraf "$artifacts_root"
+mkdirp "$artifacts_root"
 
 >&2 printf -- "- packaging release to %s -\n" "$release_path"
-pushj "$ARTIFACTS_ROOT" >/dev/null
-  # 7zip the built artifacts using max compression and multithreading
-  7za a -t7z "$release_path" ./* -m0=lzma2 -mx=9 -aoa -mfb=64 -md=32m -ms=on
+pushj "$BUILD_ROOT" >/dev/null
+  # 7zip the built artifacts using LZMA2 max compression and multithreading
+  7za a -t7z "$artifacts_path" ./* -m0=lzma2 -mx=9 -aoa -mfb=64 -md=32m -ms=on
 popj >/dev/null
 
->&2 printf "%b- release packaged successfully at %s -%b\n" "$GREEN" "$release_path" "$NC"
+>&2 printf -- "%b- release packaged successfully at %s -%b\n" "$GREEN" "$release_path" "$NC"
