deployment process close to complete

diff --git a/bin/publish/publish-module b/bin/publish/publish-module
--- a/bin/publish/publish-module
+++ b/bin/publish/publish-module
@@ -6,12 +6,12 @@
 
 ### if no arguments, throw an error
 if [ $# -eq 0 ]; then
-  >&2 echo Must specify a module directory and commit message to publish...
+  >&2 echo "Must specify a module directory and commit message to publish..."
   exit 1
 fi
 
 if [ $# -eq 1 ]; then
-  >&2 echo Must specify a commit message...
+  >&2 echo "Must specify a commit message..."
   exit 1
 fi
 
@@ -22,14 +22,14 @@ module_path="$MODULE_ROOT/$module_dir"
 
 ### if module already cloned, throw an error
 if [ ! -d "$module_path" ]; then
-  >&2 echo Module $module_dir does not exist at $module_path...
+  >&2 "echo Module $module_dir does not exist at $module_path..."
   exit 1
 fi
 
 
 #git clone $module_url $module_path 2>&1 | grep -qi "fatal" && >&2 echo "An error occurred while cloning." && exit 1
 
->&2 echo publishing $module_dir at $module_path...
+>&2 echo "publishing $module_dir at $module_path..."
 
 pushd $module_path >/dev/null
 
@@ -37,8 +37,8 @@ git add .  #| grep -qi "fatal" && >&2 echo "An error occurred while git adding."
 git commit -am "$commit_message"  #| grep -qi "fatal" && >&2 echo "An error occurred while git committing." && exit 1
 npm version patch  #| grep -qi "fatal" && >&2 echo "An error occurred while npm versioning." && exit 1
 npm publish  #| grep -qi "fatal" && >&2 echo "An error occurred while npm publishing." && exit 1
-git push origin master  #| grep -qi "fatal" && >&2 echo "An error occurred while git pushing to master." && exit 1
+git push origin --tags #| grep -qi "fatal" && >&2 echo "An error occurred while git pushing to master." && exit 1
 
 popd >/dev/null
 
->&2 echo NPM published $module_dir and changes pushed successfully!
+>&2 echo "NPM published $module_dir and changes pushed successfully!"
