changed versioning to apply git tag and skip only npm publish

diff --git a/bin/publish/publish-module b/bin/publish/publish-module
--- a/bin/publish/publish-module
+++ b/bin/publish/publish-module
@@ -15,7 +15,6 @@ if [ $# -eq 1 ]; then
   exit 1
 fi
 
-
 module_dir=$1
 commit_message=$2
 skip_npm=${3-false}
@@ -33,8 +32,8 @@ pushd $module_path >/dev/null
 
 git add -A  #| grep -qi "fatal" && >&2 echo "An error occurred while git adding." && exit 1
 git commit -am "$commit_message"  #| grep -qi "fatal" && >&2 echo "An error occurred while git committing." && exit 1
+npm version patch -m "$commit_message"   #| grep -qi "fatal" && >&2 echo "An error occurred while npm versioning." && exit 1
 if [ "$skip_npm" = false ]; then
-  npm version patch -m "$commit_message"   #| grep -qi "fatal" && >&2 echo "An error occurred while npm versioning." && exit 1
   npm publish  #| grep -qi "fatal" && >&2 echo "An error occurred while npm publishing." && exit 1
 fi
 git push --follow-tags #| grep -qi "fatal" && >&2 echo "An error occurred while git pushing to master." && exit 1
