fixed echo colors

diff --git a/bin/deploy/deploy-net b/bin/deploy/deploy-net
--- a/bin/deploy/deploy-net
+++ b/bin/deploy/deploy-net
@@ -15,7 +15,7 @@ fi
 revision="$1"
 
 if ! hash msbuild 2>/dev/null; then
-  >&2 echo "${BLUE}--MSBUILD not found, installing...--${NC}"
+  >&2 echo -e "${BLUE}--MSBUILD not found, installing...--${NC}"
   choco install microsoft-build-tools
   #http://download.microsoft.com/download/9/B/B/9BB1309E-1A8F-4A47-A6C5-ECF76672A3B3/BuildTools_Full.exe
 fi
