updated deploy-net script with options for release builds and encryption

diff --git a/bin/deploy/deploy-net b/bin/deploy/deploy-net
--- a/bin/deploy/deploy-net
+++ b/bin/deploy/deploy-net
@@ -5,13 +5,65 @@
 set -e
 . "$HOME/.tixrc"
 
-### if no arguments, throw an error
-if [ $# -lt 1 ]; then
-  >&2 echo -e "${RED}--Must specify a revision to deploy...--${NC}"
-  exit 1
+usage_short="${CYAN}Usage: deploy-net -l|-v version [-c] [-e]"
+usage_long="$usage_short\n-l: Deploy latest version of tixinc-net."
+usage_long="$usage_long\n-v: Deploy specific version (tag or hash)."
+usage_long="$usage_long\n-c: Configuration to deploy (default=Debug)."
+usage_long="$usage_long\n-e: Encrypt configuration section.${NC}"
+
+usage_short="$usage_short\nUse -h to get supported command information.${NC}"
+
+latest=false
+version=""
+configuration=Debug
+encrypt=false
+
+options=":lv:ceh"
+OPTIND=1
+while getopts "$options" opt ; do
+    case "$opt" in
+    l )
+      latest=true
+      ;;
+    v )
+      version=$OPTARG
+      ;;
+    c )
+      configuration=$OPTARG
+      ;;
+    e )
+      encrypt=true
+      ;;
+    h )
+      >&2 echo -e "$usage_long" && exit 1
+      exit 0
+      ;;
+    \?)
+      >&2 echo -e "Unknown option: -$OPTARG"
+      >&2 echo -e "$usage_short"
+      exit 1
+      ;;
+    : )
+      >&2 echo -e "Missing option argument for -$OPTARG"
+      >&2 echo -e "$usage_short"
+      exit 1
+      ;;
+    * )
+      >&2 echo -e "Unimplemented option: -$OPTARG" && exit 1
+      >&2 echo -e "$usage_short"
+      exit 1
+    esac
+done
+shift $((OPTIND-1))
+
+if [ "$latest" = true ] ; then
+  version="$(revisions -l tixinc-net)"
 fi
 
-revision="$1"
+if [ "$version" = "" ] ; then
+  >&2 echo -e "${RED}--Must specify a version to deploy (-l or -v version)--${NC}"
+  exit 1
+fi
 
 # msbuild might exist and be in path, might exist and not be in path or might not exist... thankfully MS makes this easy to install.. not
 # setup default paths an test to see if its there
@@ -33,11 +85,10 @@ if [ ! -f "$msbuild_path" ] ; then
   win_msbuild_path="msbuild"
 fi
 
+echo "--executing build-net $version--"
+build-net "$version"
 
-echo "--executing build-net $revision--"
-build-net "$revision"
-
->&2 echo "--Building and deploying artifacts revision $revision--"
+>&2 echo "--Building and deploying artifacts version $version--"
 pushd "$NET_BUILD_ROOT" >/dev/null
   >&2 echo "--Restoring packages--"
   nuget restore Tix.SelfHost.sln -PackagesDirectory packages -Verbosity quiet -NonInteractive
@@ -51,8 +102,8 @@ pushd "$NET_BUILD_ROOT" >/dev/null
   win_artifacts_root=$(echo "${win_artifacts_root:0:1}:${win_artifacts_root:1}")        # Add semicolon after drive
   >&2 echo "Building to $win_artifacts_root"
 
-  >&2 echo "Executing... -> cmd //c \"$win_msbuild_path\" Tix.Web.SelfHost\\Tix.Web.SelfHost.csproj //nologo //p:Configuration=Debug //p:OutputPath=\"${win_artifacts_root}\" //m //v:m //clp:ErrorsOnly"
-  cmd //c "$win_msbuild_path" Tix.Web.SelfHost\\Tix.Web.SelfHost.csproj //nologo //p:Configuration=Debug //p:OutputPath="${win_artifacts_root}" //m //v:m //clp:ErrorsOnly
+  >&2 echo "Executing... -> cmd //c \"$win_msbuild_path\" Tix.Web.SelfHost\\Tix.Web.SelfHost.csproj //nologo //p:Configuration=${configuration} //p:OutputPath=\"${win_artifacts_root}\" //m //v:m //clp:ErrorsOnly"
+  cmd //c "$win_msbuild_path" Tix.Web.SelfHost\\Tix.Web.SelfHost.csproj //nologo //p:Configuration=${configuration} //p:OutputPath="${win_artifacts_root}" //m //v:m //clp:ErrorsOnly
   >&2 echo "--MSBUILD finished successfully--"
 
   >&2 echo "--Cleaning packages--"
@@ -60,11 +111,12 @@ pushd "$NET_BUILD_ROOT" >/dev/null
   >&2 echo "--Packages cleaned successfully--"
 popd >/dev/null
 
-if ! hash cryptkeeper 2>/dev/null; then
-  npm install -g cryptkeeper &>/dev/null
+if [ "$encrypt" = true ] ; then
+  if ! hash cryptkeeper 2>/dev/null; then
+    npm install -g cryptkeeper &>/dev/null
+  fi
+  config_path="$NET_ARTIFACTS_ROOT/Tix.Web.SelfHost.exe.config"
+  cryptkeeper -e -n -s connectionStrings "$config_path"
 fi
 
-config_path="$NET_ARTIFACTS_ROOT/Tix.Web.SelfHost.exe.config"
-cryptkeeper -e -n -s "connectionStrings" "$config_path"
-
->&2 echo -e "${GREEN}--Artifacts revision $revision successfully deployed--${NC}"
+>&2 echo -e "${GREEN}--Artifacts version $version successfully deployed--${NC}"
