more checks and stuff around msbuild, maybe will work now

diff --git a/bin/deploy/deploy-net b/bin/deploy/deploy-net
--- a/bin/deploy/deploy-net
+++ b/bin/deploy/deploy-net
@@ -14,10 +14,24 @@ fi
 
 revision="$1"
 
-if ! hash msbuild 2>/dev/null; then
+# msbuild might exist and be in path, might exist and not be in path or might not exist... thankfully MS makes this easy to install.. not
+# setup default paths an test to see if its there
+msbuild_path="/c/Program Files (x86)/MSBuild/12.0/Bin/MSBuild.exe"
+win_msbuild_path=$(echo "$msbuild_path" | sed -e 's/^\///' -e 's/\//\\\\/g')  # strip leading slash, convert to backslash.. windows...
+win_msbuild_path=$(echo "${win_msbuild_path:0:1}:${win_msbuild_path:1}")      # Add semicolon after drive
+if [ ! -f "$msbuild_path" ] ; then
+  # Not there, lets install
   >&2 echo -e "${BLUE}--MSBUILD not found, installing...--${NC}"
   choco install microsoft-build-tools
+
+  # These downloads might help at some point
   #http://download.microsoft.com/download/9/B/B/9BB1309E-1A8F-4A47-A6C5-ECF76672A3B3/BuildTools_Full.exe
+  #choco install netfx-4.5.2-devpack
+fi
+if [ ! -f "$msbuild_path" ] ; then
+  >&2 echo -e "${RED}--MSBUILD still not found... hail mary to see if it is in default path--${NC}"
+  msbuild_path="msbuild"
+  win_msbuild_path="msbuild"
 fi
 
 >&2 echo "--Cleaning artifacts--"
@@ -38,7 +52,9 @@ pushd "$NET_BUILD_ROOT" >/dev/null
   win_artifacts_root=$(echo "${win_artifacts_root:0:1}:${win_artifacts_root:1}")        # Add semicolon after drive
   echo "Building to $win_artifacts_root"
 
-  cmd //c msbuild Tix.Web.SelfHost\\Tix.Web.SelfHost.csproj //nologo //p:Configuration=Debug //p:OutputPath=${win_artifacts_root} //m //v:m //clp:ErrorsOnly
+
+
+  cmd //c "$win_msbuild_path" Tix.Web.SelfHost\\Tix.Web.SelfHost.csproj //nologo //p:Configuration=Debug //p:OutputPath=${win_artifacts_root} //m //v:m //clp:ErrorsOnly
   echo "--MSBUILD finished successfully--"
 
   echo "--Cleaning packages--"
