updates to clone modules and sync modules

diff --git a/bin/clone/clone-module b/bin/clone/clone-module
--- a/bin/clone/clone-module
+++ b/bin/clone/clone-module
@@ -7,37 +7,37 @@ set -e
 . "$HOME/.tixrc"
 
 # Define flags
-build_flag=false
+sync_flag=false
 
-usage_short="${CYAN}Usage: clone-module [-b] module-name [relative-path]${NC}"
-usage_long="$usage_short\n-b: Clone the module to the build root instead of module root."
+usage_short="${CYAN}Usage: clone-module [-s] module-name [relative-path]"
+usage_long="$usage_short\n-s: clone the module to the sync root instead of module root.${NC}"
 
-usage_short="$usage_short\nUse -h to get supported command information."
+usage_short="$usage_short\nUse -h to get supported command information.${NC}"
 
-options=":bh"
+options=":sh"
 OPTIND=1
 while getopts "$options" opt; do
     case "$opt" in
     b )
-      build_flag=true
+      sync_flag=true
       ;;
-    h )
-      >&2 echo -e "$usage_long" && exit 1
+   h )
+      >&2 printf -- "%b\n" "$usage_long"
       exit 0
       ;;
     \?)
-      >&2 echo -e "Unknown option: -$OPTARG"
-      >&2 echo -e "$usage_short"
+      >&2 printf -- "unknown option: -%b\n" "$OPTARG"
+      >&2 printf -- "%b\n" "$usage_short"
       exit 1
       ;;
     : )
-      >&2 echo -e "Missing option argument for -$OPTARG"
-      >&2 echo -e "$usage_short"
+      >&2 printf -- "missing option argument for -%b\n" "$OPTARG"
+      >&2 printf -- "%b\n" "$usage_short"
       exit 1
       ;;
     * )
-      >&2 echo -e "Unimplemented option: -$OPTARG" && exit 1
-      >&2 echo -e "$usage_short"
+      >&2 printf -- "unimplemented option: -%b\n" "$OPTARG"
+      >&2 printf -- "%b\n" "$usage_short"
       exit 1
     esac
 done
@@ -46,16 +46,16 @@ shift $((OPTIND-1))
 
 ### if no arguments, throw an error
 if [ $# -eq 0 ]; then
-  >&2 echo -e "${RED}--Must specify a module to clone--${NC}"
+  >&2 printf -- "%b- must specify a module to clone -%b" "$RED" "$NC"
   exit 1
 fi
 
-module_name=$1
-module_dir=${2-$module_name}
+module_name="$1"
+module_dir="${2-$module_name}"
 module_root="$MODULE_ROOT"
 
-if [ "$build_flag" = true ] ; then
-  module_root="$BUILD_ROOT"
+if [ "$sync_flag" = true ] ; then
+  module_root="$SYNC_ROOT"
 fi
 
 module_url="$GITHUB_URL_TIX/$module_name"
@@ -63,10 +63,10 @@ module_path="$module_root/$module_dir"
 
 ### if module already cloned, throw an error
 if [ -d "$module_path" ]; then
-  >&2 echo -e "${RED}--Module $module_name already exists at $module_path--${NC}"
+  >&2 printf -- "%b- module %s already exists at %s -%b" "$CYAN" "$module_name" "$module_path" "$NC"
   exit 1
 fi
 
->&2 echo -e "--Cloning $module_url to $module_path...--"
-git clone "$module_url" "$module_path" 2>&1 | grep -qi "fatal" && >&2 echo "An error occurred while cloning." && exit 1
->&2 echo -e "${GREEN}--$module_name cloned successfully--${NC}"
+>&2 printf -- "- cloning %s to %s... -" "$module_url" "$module_path"
+git clone "$module_url" "$module_path" 2>&1 | grep -qi "fatal" && >&2 printf -- "An error occurred while cloning." && exit 1
+>&2 printf -- "%b- %s cloned successfully -%b" "$GREEN" "$module_name" "$NC"
diff --git a/bin/tix b/bin/tix
--- a/bin/tix
+++ b/bin/tix
@@ -76,22 +76,22 @@ while getopts "$options" opt; do
       non_interactive=true
     ;;
    h )
-      >&2 printf -- "%b" "$usage_long" && exit 1
+      >&2 printf -- "%b\n" "$usage_long"
       exit 0
       ;;
     \?)
-      >&2 printf -- "%b" "unknown option: -$OPTARG"
-      >&2 printf -- "%b" "$usage_short"
+      >&2 printf -- "unknown option: -%b\n" "$OPTARG"
+      >&2 printf -- "%b\n" "$usage_short"
       exit 1
       ;;
     : )
-      >&2 printf -- "%b" "missing option argument for -$OPTARG"
-      >&2 printf -- "%b" "$usage_short"
+      >&2 printf -- "missing option argument for -%b\n" "$OPTARG"
+      >&2 printf -- "%b\n" "$usage_short"
       exit 1
       ;;
     * )
-      >&2 printf -- "%b" "unimplemented option: -$OPTARG"
-      >&2 printf -- "%b" "$usage_short"
+      >&2 printf -- "unimplemented option: -%b\n" "$OPTARG"
+      >&2 printf -- "%b\n" "$usage_short"
       exit 1
     esac
 done
@@ -99,7 +99,7 @@ shift $((OPTIND-1))
 
 # Delete option comes first
 if [ "$uninstall_flag" = true ] ; then
-  >&2 printf -- "%b- deleting everything... -%b" "$RED" "$NC"
+  >&2 printf -- "%b- deleting everything... -%b\n" "$RED" "$NC"
   rimraf "$MODULE_ROOT"
   rimraf "$SRC_ROOT"
   rimraf "$SSH_ROOT"
@@ -123,19 +123,19 @@ fi
 
 # Install these first
 if [ "$install_required" = true ] ; then
-  >&2 printf -- "- installing required... -"
+  >&2 printf -- "- installing required... -\n"
   install-required
-  >&2 printf -- "%b- required install complete -%b" "$GREEN" "$NC"
+  >&2 printf -- "%b- required install complete -%b\n" "$GREEN" "$NC"
 fi
 
 
 if [ "$rewrite_tixrc" = true ] ; then
-  >&2 printf -- "- rewriting ~/.tixrc... -"
+  >&2 printf -- "- rewriting ~/.tixrc... -\n"
   rimraf "$CONFIG_PATH"
 fi
 if [ ! -f "$CONFIG_PATH" ] ; then
   install-tixrc
-  >&2 printf -- "- ~/.tixrc file initialized -"
+  >&2 printf -- "- ~/.tixrc file initialized -\n"
 fi
 . "$CONFIG_PATH"
 
@@ -145,10 +145,10 @@ npm-token
 . "$CONFIG_PATH"
 
 if [ ! -f "$CLI_PATH" ] || [ "$reinstall_cli" = true ] ; then
-  >&2 printf -- "- installing cli to %b... -" "$CLI_PATH"
+  >&2 printf -- "- installing cli to %b... -\n" "$CLI_PATH"
   rimraf "$CLI_PATH"
   install-cli
-  >&2 printf -- "%b- local install complete -%b" "$GREEN" "$NC"
+  >&2 printf -- "%b- local install complete -%b\n" "$GREEN" "$NC"
 fi
 
 if [ "$install_optional" = true ] ; then
@@ -172,9 +172,9 @@ if [ "$deploy_flag" = true ] ; then
 fi
 
 if [ "$non_interactive" = true ] ; then
-  printf -- "- (-n) norun flag specified, skipping cli execution... -"
+  printf -- "- (-n) norun flag specified, skipping cli execution... -\n"
   exit 0
 fi
 
-printf -- "- executing cli at %b... -" "$CLI_PATH"
+printf -- "- executing cli at %b... -\n" "$CLI_PATH"
 node "$CLI_PATH"
