updates to allow github renew token

diff --git a/bin/auth/github-token b/bin/auth/github-token
--- a/bin/auth/github-token
+++ b/bin/auth/github-token
@@ -3,8 +3,45 @@
 # Gets a git token from .tixrc or creates one
 # All stdout from this script should be redirected to stderr since the expectation is that this script will only produce a token on stdout
 
-. $HOME/.tixrc
+set -e
 
+OPTIND=1
+
+renew=false
+
+usage_short="${CYAN}Usage: github-token [-r]"
+usage_long="$usage_long\n-r: Get a fresh token from GitHub."
+
+usage_short="$usage_short\nUse -h to get supported command information."
+
+options=":rh"
+while getopts "$options" opt ; do
+    case "$opt" in
+    r ) # Gets latest annotated revision
+      renew=true
+      ;;
+    h )
+      >&2 echo -e "$usage_long" && exit 1
+      exit 0
+      ;;
+    \?)
+      >&2 echo -e "Unknown option: -$OPTARG"
+      >&2 echo -e "$usage_short"
+      exit 1
+      ;;
+    : )
+      >&2 echo -e "Missing option argument for -$OPTARG"
+      >&2 echo -e "$usage_short"
+      exit 1
+      ;;
+    * )
+      >&2 echo -e "Unimplemented option: -$OPTARG" && exit 1
+      >&2 echo -e "$usage_short"
+      exit 1
+    esac
+done
+
+. $HOME/.tixrc
 readonly GITHUB_TOKEN_KEY="GITHUB_TOKEN"
 
 ### --GIT CONFIG--
@@ -17,6 +54,7 @@ if [ ! -f "$GIT_CONFIG_PATH" ]; then
   >&2 echo "--First time git setup--"
   >&2 echo "--You will be prompted for information regarding your global git configuration--"
 fi
+
 git_config=$(git config --global -l)
 
 if ! grep -q user.name <<< "$git_config" ; then
@@ -41,7 +79,7 @@ if ! grep -q push.default <<< "$git_config" ; then
 fi
 
 ### If config file does not exist or does not contain the github token
-if [ ! -e "$CONFIG_PATH" ] || ! grep -q $GITHUB_TOKEN_KEY $CONFIG_PATH; then
+if [ "$renew" = true ] || [ ! -e "$CONFIG_PATH" ] || ! grep -q $GITHUB_TOKEN_KEY $CONFIG_PATH; then
     >&2 echo "--GitHub credentials are required to interact with the GitHub api--"
     >&2 echo "--Your basic credentials will be exchanged for a token and persisted to ${CONFIG_PATH}--"
 
@@ -91,7 +129,7 @@ if [ ! -e "$CONFIG_PATH" ] || ! grep -q $GITHUB_TOKEN_KEY $CONFIG_PATH; then
     done
 
     ### Parse out the token from the json response and stick it in the token file
-    echo $oauth_response | tr ',' '\n' | tr -d '" {}' | grep ^token: | sed s/token:// | while read token
+    echo "$oauth_response" | tr ',' '\n' | tr -d '" {}' | grep ^token: | sed s/token:// | while read token
         do
          if [ ${#token} -eq 40 ]; then
             ### Set the github token in the config
@@ -117,6 +155,8 @@ if [ ! -e "$CONFIG_PATH" ] || ! grep -q $GITHUB_TOKEN_KEY $CONFIG_PATH; then
               >&2 ssh -oStrictHostKeyChecking=no -T git@github.com
               >&2 echo "--Key added successfully--"
             fi
+
+            update-github-tokens "$token"
          fi
         done
 fi
@@ -124,11 +164,8 @@ fi
 ### Source the variable from the config file
 . "$CONFIG_PATH"
 
-
 if [ -n "$GITHUB_TOKEN" ]; then
     ### Update all github tokens
-    update-github-tokens "$GITHUB_TOKEN"
-
     echo "$GITHUB_TOKEN" | tr -d '\n'
     exit 0
 else
